# 定义一些模型参数
INITIAL_PTR = 0.12
IMMIGRANT_CHANCE_COOPERATE_WITH_SAME = 0.5  # 例如 50% 的概率与相同颜色的代理合作
IMMIGRANT_CHANCE_COOPERATE_WITH_DIFFERENT = 0.5  # 与不同颜色的代理合作的概率
DEATH_RATE = 0.1
MUTATION_RATE = 0.005
COST_OF_GIVING = 0.01
GAIN_OF_RECEIVING = 0.03
IMMIGRANTS_PER_DAY = 1
RANDOM_COLOR = ["Red", "Blue", "Yellow", "Green"]